[discord.py 2.0] Cog Changes for dpy2.
Kreusada/Kreusada-Cogs pull request #211
Opened 2022-03-10 19:09 UTC by TwinDragon

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature
- [ ] Documentation

### Description of the changes
I'm going to use this PR as something to hold any changes for d.py2 related changes for cogs. My coding knowledge is extremely minimal, but in my testing and what I am aware of, the main difference for probably a majority of these cogs will be the `avatar_url` to `avatar.url` change.

I'll leave this particular PR open for anyone else that wants to my additional d.py2 related changes that I may not be aware of, or know how to fix. I'm probably not going to have enough time to test all of the cogs here (as I don't personally use them all) and am focusing on stuff I use. I may make some preliminary changes if I happen to find them, but likely may not be tested. The only two cogs I have actually tested are the following: `advanceduptime`, `raffle`.

2022-03-23 11:18 UTC, TwinDragon commented
Recent commits in the d.py 2 side of things made pretty much most cogs will fail to load due to async changes. Looks like it's a simple adding `async` in the `__init__.py` to the `def setup` and `await` for `bot.add_cog` most likely. I'm just going off on what other people have done so far, so I'll do some tests soon.

I think all in all, may be wise to do a squash and merge when all is said and done. lol

And according to Max in the Red server, looks like cog unload will need some changes to. This might possibly be over my head, but I can get initial changes possibly to other things that I can do. We'll see.

2022-03-25 10:14 UTC, Kreusada commented
I skimmed through AC the other day and this does seem to be the way forward. I guess it would be as simple as making all `setup` and `cog_unload` methods asynchronous, and then awaiting `bot.add_cog` as you said, along with your other changes. If you have time to make those appropriate changes then feel free, I probably won't have time to make them in time for "deadline" day.

> I think all in all, may be wise to do a squash and merge when all is said and done. lol

Yeah haha, I'll be keeping this PR on hold until 3.5 is out and when we are aware of all the necessary changes.

2022-05-03 01:19 UTC, Just-Jojo requested changes
Hi! Thanks for helping out with this. I have a few remarks for this PR but otherwise it looks great

2022-05-03 01:19 UTC, Just-Jojo commented on advanceduptime/uptime.py
> +                await self.bot.remove_command("uptime")
`bot.add_command` is still a synchronous function so this will raise an error

2022-05-03 01:19 UTC, Just-Jojo commented on pingoverride/ping.py
> +                await self.bot.remove_command("ping")
Same here

2022-05-03 01:19 UTC, Just-Jojo commented on raffle/commands/informational.py
> +                icon_url=self.bot.user.avatar.url,
If the bot has a default avatar this will raise a TypeError. I'd recommend
```
getattr(self.bot.user.avatar, "url", self.bot.user.default_avatar)

2022-05-03 01:19 UTC, Just-Jojo commented on termino/termino.py
> +            await self.bot.add_command(shutdown)
Same as the first comment

2022-05-03 01:19 UTC, Just-Jojo commented on termino/termino.py
> +        await self.announce_startup.cancel()
`task.cancel` and `bot.remove_dev_env_value` are also a synchronous function so this will fail

2022-05-03 01:19 UTC, Just-Jojo commented on timestamps/timestamps.py
> +                await self.bot.remove_dev_env_value(self.__class__.__name__.lower())
Same here

2022-09-19 00:44 UTC, closed without merging