Mjolnir patch
Kreusada/Kreusada-Cogs pull request #81
Opened 2021-04-12 19:15 UTC by Just-Jojo

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature
- [ ] Documentation

### Description of the changes

Add Mjolnir :D

2021-04-12 19:55 UTC, Kreusada requested changes
A few changes which I would like to see to unify with the style of my other cogs. They are very small changes which can be committed straight from this review.

I'd also like you to add yourself to the CODEOWNERS file in the root of this repository.

```CODEOWNERS
/mjolnir/* @Just-Jojo 
```

I'd also appreciate adding the labelers. (Yes, I forgot minifier when I had released it so please include that too. You can find this file in `.github/labeler.yml`

```yaml
"Cog: Minifier":
  - minifier/*
  - docs/cog_minifier
  - docs/changelog_minifier
"Cog: Mjolnir":
  - mjolnir/*
  - docs/cog_mjolnir
  - docs/changelog_mjolnir
```

I can take care of the documentation of this cog before it is published onto this repository.

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/info.json
> +    ],
```suggestion
    "author": ["Kreusada", "Jojo"],
```

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/info.json
> +    ],
```suggestion
    "tags": ["Fun", "Marvel"],
```

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/menus.py
> +"""
```suggestion
# 99% of this code belongs to Jojo, which was authored under the MIT license.
# This cog was transferred to Kreusada (12/04/2021)
# https://github.com/Just-Jojo/JojoCogs
```

I'd rather have a secluded note than a license, but this is optional to you.

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/mjolnir.py
> +"""
```suggestion
# This code originally belonged to Jojo, which was authored under the MIT license.
# This cog was transferred to Kreusada (12/04/2021)
# https://github.com/Just-Jojo/JojoCogs
```
I'd rather have secluded notes than a license, but this is optional to you.

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/mjolnir.py
> +    __version__ = "0.1.1"
```suggestion
    __version__ = "0.1.1"
    __author__ = ["Jojo", "Kreusada"]
```

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/mjolnir.py
> +
```suggestion

    def format_help_for_context(self, ctx: commands.Context) -> str:
        context = super().format_help_for_context(ctx)
        authors = ", ".join(self.__author__)
        return f"{context}\n\nAuthor: {authors}\nVersion: {self.__version__}"
        
```

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/mjolnir.py
> +        await ctx.send(f"You have lifted Mjolnir {lifted} time{plural}")
```suggestion
        await ctx.send(f"You have lifted Mjolnir {lifted} time{plural}.")

```

It's my OCD, sorry :P

2021-04-12 19:55 UTC, Kreusada commented on mjolnir/mjolnir.py
> +                "The sky opens up and a bolt of lightning strikes the ground\nYou are worthy. Hail, son of Odin"
```suggestion
                "The sky opens up and a bolt of lightning strikes the ground\nYou are worthy. Hail, son of Odin."

```

2021-04-12 20:07 UTC, Just-Jojo commented
Made the requested changes!

2021-04-12 20:11 UTC, Kreusada commented
Perfect, just gotta write the docs and then we're to go. 🎉

2021-04-12 20:37 UTC, Kreusada approved these changes

2021-04-13 07:43 UTC, Kreusada commented
All set now. I've got the documentation in the `docs/` directory which will be merged along with this PR. This PR also won't be merged until I have finished and approved #82 and #83.

2021-04-13 08:19 UTC, Kreusada approved these changes
Thanks for contributing!

2021-04-13 08:19 UTC, merged