[Dehoister] Add ignore list and ignore users in that list
Kreusada/Kreusada-Cogs pull request #94
Opened 2021-05-19 21:57 UTC by Just-Jojo

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature
- [ ] Documentation

### Description of the changes
Adds an ignore list to have the dehoister ignore certain users. Doc strings might not be the best but it's me (:

If anything needs to be changed then lmk :D

2021-05-20 23:31 UTC, Kreusada requested changes
A few adjustments needed for this to be merged. Also, I'd like to see this ignore list respect the following commands:

- `[p]hoist clean`
- `[p]hoist scan`

Once that's done, should be all good to go. Thanks for your hard work <3

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +# Since every time this got used it was converted to a tuple just make a tuple here
```suggestion
```
We can remove this comment here, thanks for letting me know about it though, makes sense.

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +        ignored_list = await self.config.guild(ctx.guild).ignored_users
```suggestion
        ignored_list = await self.config.guild(ctx.guild).ignored_users()
```

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +        """
```suggestion
        """Add users to the ignore list.

        If on the ignore list, the dehoister will not dehoist them if 
        they have a hoisted nickname/username.
        """
```

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +        """ # This repetition is a bore >:|
```suggestion
        """Remove users from the ignore list.
        
        Once removed, they will be dehoisted by the dehoister if 
        they have a hoisted nickname/username.
        """
```

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +        """List the users ignored by the auto-dehoister"""
```suggestion
        """List the users ignored by the auto-dehoister."""
```
:)

2021-05-20 23:31 UTC, Kreusada commented on dehoister/dehoister.py
> +        """
```suggestion
        """Add and remove certain users from being ignored by the auto-dehoister."""
```
Just for styling here

2021-05-20 23:45 UTC, Just-Jojo commented
Changes have been pushed 👍

2021-05-21 10:10 UTC, Kreusada commented
Looks good to me from a quick look, have these changes been tested?

2021-05-21 15:45 UTC, Just-Jojo commented
They have indeed!

2021-05-21 18:20 UTC, Kreusada approved these changes
All set now, thanks for your patience. This looks great 👍

2021-05-21 18:22 UTC, merged